apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: streaming-app
type: Opaque
data:
  POSTGRES_USER: YWRtaW4=
  POSTGRES_PASSWORD: cGFzc3dvcmQ=
  POSTGRES_DB: c3RvcmVkYg==

