# postgres-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: standard
type: Opaque
stringData:
  POSTGRES_USER: youruser
  POSTGRES_PASSWORD: yourpassword
  POSTGRES_DB: yourdb
